server:
  port: 9093
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb
  config:
    import: "optional:configserver:http://localhost:9094/"

video:
  upload:
    path: "uploads/videos"